
CREATE TABLE events (
  id int NOT NULL PRIMARY KEY,
  type varchar(200) NOT NULL FOREIGN KEY,
  media_item_id int,
  location_id int NOT NULL FOREIGN KEY,
  name varchar(200),
  start date,
  finish date,
  reg_open datetime,
  reg_close datetime,
  reg_close datetime,
  is_public boolean,
  roster_view_mode varchar(200),
  pending_teams_view_mode varchar(200),
  is_roster_email_enabled boolean,
  sell_network_products boolean,
  contact_email varchar(200),
  organization_id int NOT NULL FOREIGN KEY,
  sport_id int,
  ranking_weight int,
  slug varchar(200),
  rank_algorithm varchar(200),
  twitter_handle varchar(200),
  youtube_key varchar(200),
  website_url varchar(200),
  creator_id int,
  created_at datetime,
  updated_at datetime,
  site_id int
)
